DROP TABLE IF EXISTS WeaveVMArchiverSei;

CREATE TABLE IF NOT EXISTS WeaveVMArchiverSei (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    NetworkBlockId INT UNIQUE,
    WeaveVMArchiveTxid VARCHAR(66) UNIQUE
);
